modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/wagyourtail/jsmacros"
license = "MPL-2.0"

[[mixins]]
config="jsmacros-common.mixins.json"

[[mixins]]
config="jsmacros-neoforge.mixins.json"

[[mods]]
modId = "jsmacros"
version = "${version}"
displayName = "JS Macros"
authors = "Wagyourtail"
description = '''
    Macro Mod for Block Game
'''

[[dependencies.jsmacros]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.10]"
ordering = "NONE"
side = "BOTH"
